import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./_components/main/header";
import { Contexts } from "./_components/_contexts";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`antialiased`}>
				<main className="bg-gray-300 h-screen">
					<Header />
					<Contexts>
						{children}
					</Contexts>
				</main>
			</body>
		</html>
	);
}
